### ISSUE TITLE
Babel plugin name is `htm` :)

### ISSUE THREAD

**Issue by danielweck** [sgtpep/csstag#5]
https://github.com/sgtpep/csstag/blob/21d30dc3fb091d73ac1cfe2a91a4ac23f1cadb2f/babel-plugin-csstag/index.js#L36

**Comment by sgtpep** [comment]
Thanks for spotting this! Sorry, I've been tied up with work, but I'll try to allocate some time very soon to fix this and those other issues you've reported.

**Comment by sgtpep** [comment]
Fixed in v0.2.1. Thank you!
