### ISSUE TITLE
Doc: Rollup plugins should be array, not object

### ISSUE THREAD

**Issue by danielweck** [sgtpep/csstag#6]
https://github.com/sgtpep/csstag/tree/master/babel-plugin-csstag#usage-with-rollup

**Comment by danielweck** [comment]
...and to pass options, the nested array syntax is needed: https://github.com/sgtpep/csstag/tree/master/babel-plugin-csstag#options

**Comment by sgtpep** [comment]
Fixed. Thanks a lot!
